# Generated by Django 2.2.7 on 2020-03-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagePath', models.CharField(default='', max_length=512)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('text', models.TextField()),
                ('short_text', models.TextField()),
            ],
        ),
    ]
