# Generated by Django 2.2.7 on 2020-03-05 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_imagestore_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagestore',
            old_name='imagePath',
            new_name='image_path',
        ),
    ]
