# Generated by Django 2.2.7 on 2020-03-06 16:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200305_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagestore',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
